name: Test Workflow

on:
  schedule:
    - cron: '*/30 * * * *'
 workflow_dispatch:

 jobs:
   hello-world:
     runs-on: ubuntu-latest
     steps:
       - name: Say Hello
         name: echo "Hello, world!"
